force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>the custom REPLACEMENT object for RetailStore(AKA Property) remember to change the name on the other one.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/areabuilding__c.field-meta.xml
<CustomField>
    <fullName>areabuilding__c</fullName>
    <label>Building Area</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/areagross__c.field-meta.xml
<CustomField>
    <fullName>areagross__c</fullName>
    <label>Gross Area of All Structures</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/arealotsf__c.field-meta.xml
<CustomField>
    <fullName>arealotsf__c</fullName>
    <label>Lot Area (Square Footage)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/availableequity__c.field-meta.xml
<CustomField>
    <fullName>availableequity__c</fullName>
    <label>Available Equity</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/bathcount__c.field-meta.xml
<CustomField>
    <fullName>bathcount__c</fullName>
    <label>Bathrooms Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/bedroomscount__c.field-meta.xml
<CustomField>
    <fullName>bedroomscount__c</fullName>
    <label>Bedrooms Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/buildingscount__c.field-meta.xml
<CustomField>
    <fullName>buildingscount__c</fullName>
    <label>Buildings Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/construction__c.field-meta.xml
<CustomField>
    <fullName>construction__c</fullName>
    <label>Construction Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/contactownermailaddressfull__c.field-meta.xml
<CustomField>
    <fullName>contactownermailaddressfull__c</fullName>
    <label>Owner Mailing Address Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/currentfirstpositionmortgagetype__c.field-meta.xml
<CustomField>
    <fullName>currentfirstpositionmortgagetype__c</fullName>
    <label>First Position Mortgage Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/deedlastsaleprice__c.field-meta.xml
<CustomField>
    <fullName>deedlastsaleprice__c</fullName>
    <label>Deed Last Sale Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/exterior1code__c.field-meta.xml
<CustomField>
    <fullName>exterior1code__c</fullName>
    <label>Exterior Wall Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/foundation__c.field-meta.xml
<CustomField>
    <fullName>foundation__c</fullName>
    <label>Foundation Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/legalsubdivision__c.field-meta.xml
<CustomField>
    <fullName>legalsubdivision__c</fullName>
    <label>Subdivision</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ltv__c.field-meta.xml
<CustomField>
    <fullName>ltv__c</fullName>
    <label>Loan-to-Value Ratio</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/ownertypedescription1__c.field-meta.xml
<CustomField>
    <fullName>ownertypedescription1__c</fullName>
    <label>Ownership Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/parcelnumberformatted__c.field-meta.xml
<CustomField>
    <fullName>parcelnumberformatted__c</fullName>
    <label>Parcel Number Formatted</label>
    <length>63</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/partyowner1namefull__c.field-meta.xml
<CustomField>
    <fullName>partyowner1namefull__c</fullName>
    <label>Owner 1 Name Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/partyowner2namefull__c.field-meta.xml
<CustomField>
    <fullName>partyowner2namefull__c</fullName>
    <label>Owner 2 Name Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/previousassessedvalue__c.field-meta.xml
<CustomField>
    <fullName>previousassessedvalue__c</fullName>
    <label>Previous Assessed Value</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/propertyaddressfull__c.field-meta.xml
<CustomField>
    <fullName>propertyaddressfull__c</fullName>
    <inlineHelpText>THE SFMAPSAPI (ATTOM) STREET ADDRESS</inlineHelpText>
    <label>Property: Address Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/propertyusestandardized__c.field-meta.xml
<CustomField>
    <fullName>propertyusestandardized__c</fullName>
    <inlineHelpText>(untranslated codes)

409 : Tax Exempt Public Housing...
463 : Agricultural,Improved,Rural...
464 : Salon / Barber / Hair Dresser...
471 : Multi-Family Residential / Apartment Building (only in Pottawattamie County, IA?)</inlineHelpText>
    <label>Property Use</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/roofmaterial__c.field-meta.xml
<CustomField>
    <fullName>roofmaterial__c</fullName>
    <label>Roof Material</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/roomscount__c.field-meta.xml
<CustomField>
    <fullName>roomscount__c</fullName>
    <label>Rooms Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/situscounty__c.field-meta.xml
<CustomField>
    <fullName>situscounty__c</fullName>
    <label>County</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/statusowneroccupiedflag__c.field-meta.xml
<CustomField>
    <fullName>statusowneroccupiedflag__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Owner Occupied Flag</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/storiescount__c.field-meta.xml
<CustomField>
    <fullName>storiescount__c</fullName>
    <label>Stories Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/structurestyle__c.field-meta.xml
<CustomField>
    <fullName>structurestyle__c</fullName>
    <label>Structure Style Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/taxassessedvalueimprovements__c.field-meta.xml
<CustomField>
    <fullName>taxassessedvalueimprovements__c</fullName>
    <label>Tax Assessed Value Improvements</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/taxassessedvaluetotal__c.field-meta.xml
<CustomField>
    <fullName>taxassessedvaluetotal__c</fullName>
    <label>Tax Assessed Value Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/taxbilledamount__c.field-meta.xml
<CustomField>
    <fullName>taxbilledamount__c</fullName>
    <label>Tax Billed Amount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/taxmarketvalueimprovements__c.field-meta.xml
<CustomField>
    <fullName>taxmarketvalueimprovements__c</fullName>
    <label>Tax Market Value Improvements</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/taxmarketvaluetotal__c.field-meta.xml
<CustomField>
    <fullName>taxmarketvaluetotal__c</fullName>
    <label>Tax Market Value Total</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/unitscount__c.field-meta.xml
<CustomField>
    <fullName>unitscount__c</fullName>
    <label>Units Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/yearbuilt__c.field-meta.xml
<CustomField>
    <fullName>yearbuilt__c</fullName>
    <label>Year Built</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JsonUtility.cls
/**
 * Created by Devin on 5/9/2024.
 */

public class JsonUtility {

    public static String ParseByToken(String body, String tokenName){
        String returnValue;
        JSONParser parser = JSON.createParser(body);

        while(parser.nextToken() != null){
            if(parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == tokenName){
                parser.nextToken();
                returnValue = parser.getText();
            }
        }
        return returnValue;
    }
    //Alternative JsonParser that goes until {{tokenBreak}} is found...
    public static String ParseByTokenUntil(String body, String tokenName, String tokenBreak){
        String returnValue;
        JSONParser parser = JSON.createParser(body);

        while (parser.nextToken() != null && parser.getText() != tokenBreak) {
            if (parser.getCurrentToken() == JSONToken.FIELD_NAME && parser.getText() == 'id'){
                parser.nextToken();
                returnValue = parser.getText();
            }
        }
        return returnValue;
    }
//    public static List<Property__c> ParseBySFMapsResponse(String body,String matchTopic){
//        List<Property__c> updateableProperties = new List<Property__c>();
//        String value;
//        String empt = '';
//        String z = '0';
//        JSONParser parser = JSON.createParser(body);
//        Property__c prop = new Property__c();
//        System.debug(SfMapsRetriever.keyMap);
//        System.debug(JSON.serializePretty(SfMapsRetriever.keyMap));
//        Integer matchTopicStart=body.indexOf(matchTopic);
//
//        while(parser.nextToken() != null){
//            switch on parser.getText() {
//
//                when 'value'{
//                    parser.nextToken();
//                    value = parser.getText();
//                    if (value == 'null') {
//                        value = null;
//                    }
//                }
//                when 'topic_id'{
//                    parser.nextToken();
//                    switch on parser.getText(){
//                        when 'propertyaddressfull'{
//                            System.debug('\rmatchTopic='+matchTopic+' (current value='+value+') '+prop.get(matchTopic+'__c')+' filterStreetMaps=='+ SfMapsRetriever.keyMap.get((String)prop.get(matchTopic+'__c')));
//                            prop.Id=SfMapsRetriever.keyMap.get((String)prop.get(matchTopic+'__c')); //matching property here
//                            System.debug(prop.get(matchTopic+'__c')+'...FOUND->'+prop);
//                            prop.propertyaddressfull__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'partyowner1namefull'{
//                            prop.partyowner1namefull__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'partyowner2namefull'{
//                            prop.partyowner2namefull__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'contactownermailaddressfull'{
//                            prop.contactownermailaddressfull__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'statusowneroccupiedflag'{
//                            prop.statusowneroccupiedflag__c = Boolean.valueOf(value ?? 'false');
//                        }
//                        when 'construction'{
//                            prop.construction__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'structurestyle'{
//                            prop.structurestyle__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'legalsubdivision'{
//                            prop.legalsubdivision__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'situscounty'{
//                            prop.situscounty__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'parcelnumberformatted'{
//                            prop.parcelnumberformatted__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'foundation'{
//                            prop.foundation__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'roofmaterial'{
//                            prop.roofmaterial__c=String.valueOf(value) ?? empt;
//                        }
//                        when 'roomscount'{
//                            prop.roomscount__c = Integer.valueOf(value ?? z);
//                        }
//                        when 'bathcount'{
//                            prop.bathcount__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'bedroomscount'{
//                            prop.bedroomscount__c = Integer.valueOf(value ?? z);
//                        }
//                        when 'storiescount'{
//                            prop.storiescount__c = Integer.valueOf(value?? z);
//                        }
//                        when 'unitscount'{
//                            prop.unitscount__c = Integer.valueOf(value ?? z);
//                        }
//                        when 'buildingscount'{
//                            prop.buildingscount__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'areabuilding'{
//                            prop.areabuilding__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'areagross'{
//                            prop.areagross__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'arealotsf'{
//                            prop.arealotsf__c = Decimal.valueOf(String.valueOf(value?? z));
//                        }
//                        when 'ownertypedescription1'{
//                            prop.ownertypedescription1__c=String.valueOf(value ?? empt);
//                        }
//                        when 'currentfirstpositionmortgagetype'{
//                            prop.currentfirstpositionmortgagetype__c=String.valueOf(value ?? empt);
//                        }
//                        when 'availableequity'{
//
//                            prop.availableequity__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'ltv'{
//
//                            prop.ltv__c=Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'taxassessedvaluetotal'{
//                            prop.taxassessedvaluetotal__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'taxassessedvalueimprovements'{
//                            prop.taxassessedvalueimprovements__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'previousassessedvalue'{
//                            prop.previousassessedvalue__c=Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'taxbilledamount'{
//                            prop.taxbilledamount__c=Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'taxmarketvalueimprovements'{
//                            prop.taxmarketvalueimprovements__c=Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'taxmarketvaluetotal'{
//                            prop.taxmarketvaluetotal__c=Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'yearbuilt'{
//                            prop.yearbuilt__c = Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'deedlastsaleprice'{
//                            prop.deedlastsaleprice__c=Decimal.valueOf(String.valueOf(value ?? z));
//                        }
//                        when 'exterior1code'{
//                            prop.exterior1code__c=String.valueOf(value);
//                        }
//                        when 'propertyusestandardized'{
//                            prop.propertyusestandardized__c=String.valueOf(value) ?? empt;
//                        }
//                    }
//                }
//                when 'geoid'{
//                    parser.nextToken();
//                    parser.nextToken();
//                    parser.nextToken();
//                    updateableProperties.add(prop);
//                }
//                when 'popup'{
//                    prop = new Property__c();
//                }
//            }
//        }
//        System.debug(JSON.serializePretty(updateableProperties));
//        return updateableProperties;
//    }

    public static String escapeCSV(String value) {
        if (value == null) return ''; if (value.contains(',') || value.contains('\n') || value.contains('"')) { value = value.replace('"', '""');
            return '"' + value + '"';
        }
        return value;
    }

}