force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>the custom REPLACEMENT object for RetailStore(AKA Property) remember to change the name on the other one.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/AccountId__c.field-meta.xml
<CustomField>
    <fullName>AccountId__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Properties</relationshipLabel>
    <relationshipName>Properties</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/WorkOrderRelationHandler.cls
/**
 * Created by Devin on 8/12/2024.
 */

public with sharing class WorkOrderRelationHandler {


    @InvocableMethod(Label = 'Check Unrelated Appointments' Category = 'Account')
    public static void RelateUnrelatedAppointmentsFromAccountIds(List<Id> ids){
        for(Id id : ids){ Set<Id> idSet = new Set<Id>{id}; Map<Id,Account> accountMap = WorkOrderRelationHelper.getAccountMap(idSet);
            for(Account a : accountMap.values()){
                WorkOrderRelationHelper.RelatedUnrelatedAppointments(a);
            }
        }
    }
    public static void RelateUnrelatedAppointmentsFromPropertyList(List<Property__c> properties){
        for(Property__c p : properties){
            Set<Id> Ids = new Set<Id>{p.AccountId__c};
            Map<Id,Account> accountMap = WorkOrderRelationHelper.getAccountMap(Ids);
            System.debug(accountMap);
            for(Account a : accountMap.values()){
                WorkOrderRelationHelper.RelatedUnrelatedAppointments(a);
            }
        }
    }

}