force-app/main/default/objects/Account_Property_Relationship__c/Account_Property_Relationship__c.object-meta.xml
<CustomObject>
    <label>Account Property Relationship</label>
    <nameField>
        <displayFormat>APR-{0000000}</displayFormat>
        <label>Account-Property Relationship Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Property Relationships</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Account_Property_Relationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Property Relationships</relationshipLabel>
    <relationshipName>Account_Property_Relationships</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Account_Property_Relationship__c/fields/Property__c.field-meta.xml
<CustomField>
    <fullName>Property__c</fullName>
    <label>Property</label>
    <referenceTo>Property__c</referenceTo>
    <relationshipLabel>Account Property Relationships</relationshipLabel>
    <relationshipName>Account_Property_Relationships</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Property__c/Property__c.object-meta.xml
<CustomObject>
    <description>the custom REPLACEMENT object for RetailStore(AKA Property) remember to change the name on the other one.</description>
    <label>Property</label>
    <nameField>
        <label>Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Properties</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Property__c/fields/contactownermailaddressfull__c.field-meta.xml
<CustomField>
    <fullName>contactownermailaddressfull__c</fullName>
    <label>Owner Mailing Address Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/Mailing_Only_Address__c.field-meta.xml
<CustomField>
    <fullName>Mailing_Only_Address__c</fullName>
    <description>probably temp</description>
    <label>Mailing Only Address</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/partyowner1namefull__c.field-meta.xml
<CustomField>
    <fullName>partyowner1namefull__c</fullName>
    <label>Owner 1 Name Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/partyowner2namefull__c.field-meta.xml
<CustomField>
    <fullName>partyowner2namefull__c</fullName>
    <label>Owner 2 Name Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Property__c/fields/propertyaddressfull__c.field-meta.xml
<CustomField>
    <fullName>propertyaddressfull__c</fullName>
    <inlineHelpText>THE SFMAPSAPI (ATTOM) STREET ADDRESS</inlineHelpText>
    <label>Property: Address Full</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/SFMapsAPI.cls
/**
 * Created by BENJAMIN on 1/17/2025.
 */

public with sharing class SFMapsAPI {
    public static final Set<String> mailingOnlyTypes =new Set<String>{
            'APT','STE','UNIT','LOT','#','PO BOX','TRLR','DRWY','BLDG','FLR','ROOM','RM',
            'BOX','OFC','SPC','UPPR','LOWR','BSMT','REAR','FRNT','RM','SIDE','SLIP','STOP'
    };
    public static List<String> allTopics=new List<String>{'propertyaddressfull','propertyaddresszip','propertyaddresscity', 'propertylatitude', 'propertylongitude',
            'partyowner1namefull','partyowner2namefull','contactownermailaddressfull','contactownermailaddresscity','statusowneroccupiedflag','construction','structurestyle','legalsubdivision','situscounty',
            'parcelnumberformatted','parcelnumberraw','foundation','roofmaterial','roomscount','bathcount','bedroomscount','storiescount','unitscount','buildingscount','areabuilding',
            'areagross','arealotsf','fireplacecount','ownertypedescription1','ownertypedescription2','currentfirstpositionmortgagetype','currentsecondpositionmortgagetype',
            'availableequity','ltv','currentfirstpositionopenloaninterestrate','ownershipvestingrelationcode','deedlastsaledate',
            'taxyearassessed','taxassessedvaluetotal','taxassessedvalueland','taxassessedvalueimprovements','previousassessedvalue','taxbilledamount','taxmarketvalueland',
            'taxmarketvalueimprovements','taxmarketvaluetotal','taxfiscalyear','yearbuilt','yearbuilteffective','propertyjurisdictionname','deedlastsaleprice','exterior1code',
            'propertyjurisdictionname','propertyusestandardized','currentsecondpositionopenloaninterestrate','propertyusegroup','hvacheatingfuel','hvacheatingdetail','hvaccoolingdetail','parkinggarage'
    };
    public static String source;
    public static String streetTopic;
    public static String cityTopic;
    public static Boolean isRouteSplitting;
    public static String badChars;
    public List<Property__c> props{get;set;}
    public static List<Integer> geographicIds=new List<Integer>();
    public List<String> topics = new List<String>();
    public SfMapsRetriever sfmr{get;set;}
    public List<Property__c> insertProps{get;set;} //like LANDLORDS.
    // namematch score=0,AND*OR:(propertyaddressfull!=contactownermailaddressfull, ownertypedescription1!='INDIVIDUAL',propertyusetype!='Residential%',unitscount>1 or null,statusowneroccupiedflag=FALSE)
    public static void setInitials(String streetTpc,String cityTpc,String src,Boolean routeSplit,String badCharacters){
        source=src;
        cityTopic=cityTpc;
        streetTopic=streetTpc;
        isRouteSplitting=routeSplit;
        badChars=badCharacters;
    }//  ↙⎻⎻⎻⎻CONSTRUCTOR⎻⎻#1⎻-⎽‗(sets up static class)//
    public SFMapsAPI(String source,String streetTopic,String cityTopic,Boolean isRouteSplitting,String badChars){
        setInitials(streetTopic,cityTopic,source,isRouteSplitting,badChars);
        this.sfmr = new SfMapsRetriever(source,streetTopic,cityTopic,isRouteSplitting,badChars); //sfmr constructor #1 »»—–—→> INITIALIZER
        System.debug('\rSfmAPI(c1):ENDING:(Success. SFMapsAPI & SFMapsRetriever static variables initialized; SfmAPI & sfmr1 instantiated)...\r\t\tsource:{SFMapsAPI='+SFMapsAPI.source+'; SfMapsRetriever='+SfMapsRetriever.file_id+'\r\t\tstreetTopic:{SFMapsAPI='+SFMapsAPI.streetTopic+'; SfMapsRetriever='+SfMapsRetriever.streetTopic+'}\r\t\tcityTopic:{SFMapsAPI='+SFMapsAPI.cityTopic+'; SfMapsRetriever='+SfMapsRetriever.cityTopic+'}\r\t\tbadChars:{SFMapsAPI='+SFMapsAPI.badChars+'; SfMapsRetriever='+SfMapsRetriever.badChars+'}\r\t\tisRouteSplitting:{SFMapsAPI='+SFMapsAPI.isRouteSplitting+'; SfMapsRetriever='+SfMapsRetriever.isRouteSplitting+'}');
    }//  ↙⎻⎻⎻⎻CONSTRUCTOR⎻⎻#2⎻-⎽‗(searches for geoIds)//
    public SFMapsAPI(List<Property__c> props) {
        this.props = props;
        System.debug('\rSfmAPI(c2): Starting with '+this.props.size()+' props.');
        SfMapsRetriever.makeFilterMaps(this.props);
        makeGeoIdRequests(this.props); //constructor #2 »»—–—→> GEO IDS
        System.debug('\rSfmAPI(c2): Ending with '+this.props.size()+',\r\t\t\t\t\t\t'+geographicIds.size()+' GeographicIds \r\t\t\t\t['+geographicIds+']');
    }//  ↙⎻⎻⎻⎻CONSTRUCTOR⎻⎻#3⎻-⎽‗(sets up static class)//
    public SFMapsAPI(List<Property__c> props,List<String>inTopics){
        this.topics = topicsChecked(inTopics);
        this.props=props;
        System.debug('\rSfmAPI(c3): Starting with '+this.props.size()+' props.');
        this.sfmr = new SfMapsRetriever(this.props,this.topics,geographicIds); //constructor #3 »»—–—→> HOSTED DATA
        if(this.sfmr.response!=null&&this.sfmr.response.containsKey('data')){
            Map<Id,Property__c>matchGuideMap=new Map<Id,Property__c>(this.props);
            this.props=this.sfmr.procHostedDataResponse(this.sfmr.response);//            System.debug('SfmAPI c3: sfmr.response:\r'+this.sfmr.response);
            System.debug('SfmAPI(c3): Processing Hosted Data Response:\r foundProps(size='+this.props.size()+')—>\r'+JSON.serializePretty(this.props));
            if(this.props.size()>0){ // if foundProps contains anything this runs.
                this.props=this.sfmr.nameMatcher(this.props,matchGuideMap);
                System.debug('\rSfmAPI(c3): Clearing Found Props of Duplicate Ids (namematch):\r nameMatchedProps(size='+this.props.size()+')—>\r'+JSON.serializePretty(this.props));
                this.props = removePostCallProblems(this.props);
                System.debug('SfmAPI(c3): Post-Processing Found&Matched Props:\r Final Props(size='+this.props.size()+')—>\r'+JSON.serializePretty(this.props));
            }
        }
    }
    public static List<String> topicsChecked(List<String> inTopics){
        Set<String> topicDedupe = new Set<String>{'propertyaddressfull','partyowner1namefull','contactownermailaddressfull'};
        for(String inTopic : inTopics){
            if(allTopics.contains(inTopic)){
                topicDedupe.add(inTopic); }
        }
        return new List<String>(topicDedupe);
    }
    public void makeGeoIdRequests(List<Property__c>props){
        for(String searchKey : SfMapsRetriever.searchMap.keySet()){
            this.sfmr = new SfMapsRetriever(props,searchKey);//constructor #2 List<sfmr>...runs all sfmr Constr2 methods,produces the reqString,sends it,& then response.
            if(this.sfmr.reqString!=null&&this.sfmr.response!=null&&this.sfmr.response.containsKey('data')){
                List<Integer> geoIds = this.sfmr.procGeoIdResponse(this.sfmr.response);
                geographicIds.addAll(geoIds);
                System.debug('sfmApi(c2):makeGeoIdRequests:'+searchKey+'\rgeoIds in response='+geoIds+'\r... TOTAL geographicIds so far (size='+geographicIds.size()+')');
            }
        }
    }
    public List<Property__c> removePostCallProblems (List<Property__c> props){ //these are all matched by keymap so we can assume the streettopic value contained all the address__Street__s shtuf
        this.insertProps = new List<Property__c>();
        List<Property__c> updateProps = new List<Property__c>();
        String mailingOnlyStub;
        for(Property__c p : props){
            Boolean isSubunit=false;
            if(p.propertyaddressfull__c!=null&&p.contactownermailaddressfull__c!=null){
                if(mailingOnlyTypes.contains((((p.contactownermailaddressfull__c.substringAfter(p.propertyaddressfull__c)).trim()).substringBefore(' ')).trim())){
                    mailingOnlyStub = (((p.contactownermailaddressfull__c.substringAfter(p.propertyaddressfull__c)).trim()).substringBefore(' ')).trim();
                    System.debug('p.contactownermailaddressfull__c—>'+p.contactownermailaddressfull__c+'!!!('+mailingOnlyStub);
                    isSubunit = mailingOnlyTypes.contains(mailingOnlyStub);
                    if(isSubunit){
                        mailingOnlyStub = mailingOnlyStub+p.contactownermailaddressfull__c.substringAfterLast(' '+mailingOnlyStub+' ');
                    }
                } else if(p.contactownermailaddressfull__c.contains('PO BOX')){ mailingOnlyStub='PO BOX'+p.contactownermailaddressfull__c.substringAfterLast('PO BOX');
                }
            } else if(p.contactownermailaddressfull__c!=null&&mailingOnlyTypes.contains(((p.contactownermailaddressfull__c.substringBeforeLast(' ')).substringAfterLast(' ')).trim())){
                mailingOnlyStub = ((p.contactownermailaddressfull__c.substringBeforeLast(' ')).substringAfterLast(' ')).trim();
                System.debug('p.contactownermailaddressfull__c—>'+p.contactownermailaddressfull__c+'!!!('+mailingOnlyStub+')');
                isSubunit = mailingOnlyTypes.contains(mailingOnlyStub);
                if(isSubunit){
                    mailingOnlyStub = mailingOnlyStub+p.contactownermailaddressfull__c.substringAfterLast(' '+mailingOnlyStub+' ');
                }
            } else if(p.propertyaddressfull__c!=null&&mailingOnlyTypes.contains(((p.propertyaddressfull__c.substringBeforeLast(' ')).substringAfterLast(' ')).trim())){
                mailingOnlyStub = ((p.propertyaddressfull__c.substringBeforeLast(' ')).substringAfterLast(' ')).trim();
                System.debug('p.propertyaddressfull__c—>'+p.propertyaddressfull__c+'!!!('+mailingOnlyStub+')'); isSubunit = mailingOnlyTypes.contains(mailingOnlyStub);
                if(isSubunit){ mailingOnlyStub = mailingOnlyStub+p.propertyaddressfull__c.substringAfterLast(' '+mailingOnlyStub+' ');
                }
            }
            if(isSubunit){
                if(p.Mailing_Only_Address__c!=mailingOnlyStub){
                    System.debug('Mailing Only Update for : '+p.Name+'...new Val='+mailingOnlyStub);
                    p.Mailing_Only_Address__c=mailingOnlyStub; //gets hit either way i guess
                    if(subUnitScour(p)){
                        System.debug('snagged a mailing only bitch.'+p.Id+' '+p.contactownermailaddressfull__c);
                        this.insertProps.add(p);
                    }
                }
            } else {updateProps.add(p);}
            updateProps.add(p);
        }
        System.debug('sfmApi(c3): –—FINAL–TALLY–—> (UNIQUE UPDATERS:'+new Set<Property__c>(updateProps).size()+' / UPDATERS: '+updateProps.size()+' /  MATCHED: '+props.size()+' )');
        updateProps=new List<Property__c>(new Set<Property__c>(updateProps));
        return updateProps;
    }
    public static Boolean subUnitScour(Property__c p){
        Boolean isInserter=true; //if(isInserter){updateProps.remove(updateProps.indexOf(p));p. insertProps.add(p);// just update mailingOnlyAddress field//mailing_only_addr__c has different value than mailingstub
        String partyOwnerClump;
        if (p.partyowner1namefull__c!=null) {
            partyOwnerClump = p.partyowner1namefull__c;
        }
        if (p.partyowner2namefull__c!=null) {
            partyOwnerClump = partyOwnerClump + '+' + p.partyowner2namefull__c;
        }
        if (partyOwnerClump!=null&&(partyOwnerClump.length()>3)){
            if(partyOwnerClump.contains('[not provided]')){ partyOwnerClump=(partyOwnerClump.remove('[not provided]')).trim();
            }
            if(p.Account_Property_Relationships__r.size()>0){
                for (Account_Property_Relationship__c apr : p.Account_Property_Relationships__r) {
                    if(apr.Account__r.Name.contains(' & ')){
                        if(((apr.Account__r.Name.substringAfter(' ').substringBefore(' & ')).length()>1&&partyOwnerClump.containsIgnoreCase(apr.Account__r.Name.substringAfter(' ').substringBefore(' & ')))||((apr.Account__r.Name.substringAfterLast(' ')).length()>1&&partyOwnerClump.containsIgnoreCase(apr.Account__r.Name.substringAfterLast(' ')))){ isInserter=false;
                        }
                    } else if(apr.Account__r.Name.contains(' ')){
                        if(apr.Account__r.Name.substringAfter(' ').length()>1&&partyOwnerClump.containsIgnoreCase(apr.Account__r.Name.substringAfter(' '))){ isInserter=false;
                        } else if(apr.Account__r.Name.substringBefore(' ').length()>1&&partyOwnerClump.containsIgnoreCase(apr.Account__r.Name.substringAfter(' '))){ isInserter=false;
                        }
                    } else if(apr.Account__r.Name.length()>1&&partyOwnerClump.containsIgnoreCase(apr.Account__r.Name)) { //just contains a wordisInserter=false;
                    }
                }
            } else if (p.Leads__r.size() > 0) {
                for (Lead l : p.Leads__r) {
                    if (partyOwnerClump.containsIgnoreCase(l.LastName)) {
                        isInserter=false;
                    }
                }
            }
        } else { isInserter=false; }//need owner names
        return isInserter;
    }
    public static List<PropertyPirateShip.pirateShipFilter>ScavengePrep(){
        List<PropertyPirateShip.pirateShipFilter>pirateFilters=new List<PropertyPirateShip.pirateShipFilter>();
        return pirateFilters; }
    public static Map<String,Object>Scavenger(List<Property__c>unmatchedProps){
        //return extra markers for stuff we can know about who we're after. Mess around with piratefilters to make them usable for topic filtering as a parameter.
        Map<String,Object>scavengedRes=new Map<String,Object>(); ScavengingPlan(ScavengePrep());
        return scavengedRes; }

    public static void ScavengingPlan(List<PropertyPirateShip.pirateShipFilter>pirateFilters){ }
}
// ↕ : ꜜꜛ↖←↙↓↕↘→↗ ⇒↔ ⇔ ⬊⬇⬋⬅⬉⬆⬈➡͢⭰⭶⭱⭷⭲⭸⭳⭹🡸🡼🡹🡽🡺🡾🡻🡿    // <>:   ˂˃,{},[],(),‹›,«〈〉,《》,◀▶,◁▷ ≤≥,≪≫,ʿʾ˓˒,☜☞,⊂⊃,⊆⊇,〔〕,【】
// v^:  vVⱽ,∇∆,∨∧,˅˄,﹀︿,︾︽,▽△,▼▲,ˆˇ,ᵕᵔ,˕˔,ᵥᵧᵞᴧ,۷۸,ˎˏˊˋ,ꞈλͮ  // nu:   Πᴨ,uU,∏,ՍՌ,∩∪,⌒,︵︶,︷︸,︹︺,︻︼,﹇﹈,ᴫ
// | :   ꞌǀǁ⁞ㅣ¦|‖│║┃╈ ╉†‡Iㅏ⊥ㅛㅜ▒ƖI!‼ǃꜞᵢ¡,\/⁄                 // _-:    ‗ˍ_﹍―‒ㅡ─—–-▬━￣‾ˉ¨﹊"'…‥⎺⎻⎼⎽⎯
// LJ:  ∠,՟﹂﹄」˩』,└┕┖┗,∟լ,յȷ,⌡,ʟᴸᴶʲɹɺㅢ,└┘╘╛╙╜╚╝           // r7    ᄼᅎᄽᅏᄾᅐᄿᅑ,⌐「『┌┎┍┏⌠ꞄՐ,˥Ꞁ¬﹁﹃￢,ꭈꭋ,ſŕŗřᴦʴʳᵣ⁷ ┌┐╒╕╓╖╔╗                                                    //    = :   =═≡〓≒ʭ±˖÷⸗ꟾ■□▣ˌ.:;,ːˑ`۱、〃“”‛’‟„‘‚´῾∬∫
// * :   ※•♩♪♬♭♣♤♥♨♧。◆◇◈○●◎◐◑★☆☏☎♀♂♠♡∴¤